export default {
  // recruit
  GET_RECRUITS: 'GET_RECRUITS',
  GET_RECRUIT: 'GET_RECRUIT',
  CREATE_RECRUIT: 'CREATE_RECRUIT',
  UPDATE_RECRUIT: 'UPDATE_RECRUIT',
  DELETE_RECRUIT: 'DELETE_RECRUIT',
} as const;
